### ISSUE TITLE
Problem: Sign in with Email not integrated

### ISSUE THREAD

**Issue by teodorus-nathaniel** [holdex/thirdweb-svelte#5]
sub of:
- https://github.com/holdex/marketing/issues/85

**Comment by teodorus-nathaniel** [comment]
Sign in with email is not included in the list of necessary provider. Will close this for now.

**Comment by zolotokrylin** [comment]
Let's keep it open, but not execute on it for now 🙏

**Comment by teodorus-nathaniel** [comment]
Closed in favor of https://github.com/Ozean-L2/thirdweb-svelte/issues/1

**Comment by angelicawill** [comment]
@teodorus-nathaniel can you provide ETA for this?

**Comment by teodorus-nathaniel** [comment]
it will take 1 day for me to finish this once I started, but as I will finish the export private key goal first, I think tomorrow should be done
